# Harmonize All - Apply Design System to Entire Application
name: "harmonize-all"
description: "Analyze Advanced page and apply design system to entire web application with approval checkpoints"
author: "BMad"

# Critical variables from agent sidecar context
config_source: "{project-root}/bmad/bmb/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated

# Agent-specific paths
agent_folder: "{project-root}/bmad/agents/design-guardian"
sidecar_folder: "{agent_folder}/design-guardian-sidecar"
knowledge_folder: "{sidecar_folder}/knowledge"

# Design system references
design_reference: "{project-root}/src/components/AdvancedPlaygroundDemo.tsx"
design_system_doc: "{knowledge_folder}/design-system.md"
patterns_doc: "{knowledge_folder}/patterns.md"

# Components to harmonize
components_path: "{project-root}/src/components"

# Module path and component files
installed_path: "{agent_folder}/workflows/harmonize-all"
template: false # Action workflow - no template needed
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Harmonization report output
harmonization_report: "{output_folder}/harmonization-report-{date}.md"

# Invocation control
standalone: true
